---
- name: instalando agente em todas as maquinas.
  package:
   name: puppet-agent
   update_cache: yes

- name: dando um start no puppet quando for redhat
  service:
   name: puppet
   state: restarted
  when: ansible_os_family == "RedHat" 
