---

- name: Criando os usuarios padroes
  user:
   name: "{{item.nome}}"
   shell: "{{item.bash}}"
   password: "{{item.senha}}"
   home: "{{item.home}}"
  with_items:
   - {nome: paulo, bash: /bin/bash, senha: '$1$lvnwoYg3$6rwA5Aicsx52TAs8vuV6h1', home: /srv/paulo}
   - {nome: developer, bash: /bin/bash, senha: '$1$lvnwoYg3$6rwA5Aicsx52TAs8vuV6h1', home: /srv/developer}
   - {nome: devops, bash: /bin/bash, senha: '$1$lvnwoYg3$6rwA5Aicsx52TAs8vuV6h1', home: /srv/devops}
