---
- name: instalando pacotes genericos
  hosts: all
  tasks:
   
    - name: Instalando pacotes em comum
      package: 
      name:
       -  vim
       - htop
       - cowsay
       - figlet
      state: present

    - name: instalando pacotes somente debian
      package:
       name:
        - apache2
      when: ansible_os_family == "Debian"
 
    - name: instalando pacotes somente debian
      package:
       name:
        - httpd
        - epel-release
      when: ansible_os_family == "RedHat"
