- name: instalando o apache no Debian
  package:
   name: apache2
   state: present
  when: ansible_os_family == "Debian"

- name: instalando o apache no redhat
  package:
   name: httpd
   state: present
  when: ansible_os_family == "RedHat"

